# Generated by Django 4.2.1 on 2023-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_profile_national_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="user", new_name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
