# Generated by Django 4.2.1 on 2023-08-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_rename_username_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="image", new_name="profile_image",
        ),
    ]
