# Generated by Django 4.2.4 on 2023-08-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
    ]
