# Generated by Django 4.2.1 on 2023-08-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="ijk",),
    ]
