# Generated by Django 4.2.4 on 2023-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_body_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='توضیخات خود را وارد کنید', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='mytitle', help_text='عنوان خود را انتخاب کنید', max_length=50, verbose_name='عنوان'),
        ),
    ]
